### ISSUE TITLE
Can't use models: PFG, MoistMix, Moedel

### ISSUE THREAD

**Issue by jug-dev** [Sygil-Dev/nataili-model-reference#95]
I've tried loading all sd1 baseline models into Stable Horde and only these three fail. Pretty sure there is something horribly wrong with each of them (or their config).

**Comment by db0** [comment]
What is your `max_models_to_download` set to?

**Comment by db0** [comment]
OK I had a crash with it. @AlRlC does this maybe need a `?type=Model&format=PickleTensor` at the download as well?

**Comment by AlRlC** [comment]
I believe this is a server reliability issue on civitai's end.
Moedel had an incorrect download URL which was fixed here:  https://github.com/Sygil-Dev/nataili-model-reference/commit/5326f6f11b0c5a894286f951c4ce7e37e6337ec2

Confirmed with jug-dev the issue is resolved on their end.

**Comment by jug-dev** [comment]
My `max_models_to_download` is set to 200. But as [AlRlC](https://github.com/AlRlC) mentioned, all models now work.
